#!/bin/bash

#SBATCH --partition=t1small
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --job-name=concat_fst
#SBATCH --output=/center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/job_outfiles/fst/concat_fst_TG-KZ_%A.out
#SBATCH --error=/center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/job_outfiles/fst/concat_fst_TG-KZ_%A.err


for i in /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045152.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045153.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045154.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045155.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045156.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045157.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045158.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045159.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045160.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045161.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045162.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045163.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045164.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045165.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045166.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045167.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045168.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045169.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045170.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045171.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045172.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045173.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045174.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045175.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045176.1_polymorphic_folded.sfs.pbs.fst.txt /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_NC_045177.1_polymorphic_folded.sfs.pbs.fst.txt
do tail -n +2 $i >> /center1/GLASSLAB/salmgren/lcwgs/ebs_popgen/fst/pherr_TG-KZ_wholegenome_fst_folded.txt; done
